"""
Isolates the question-generating task (TASK1) from the rest of the code in prompt_llm.py, so that it can be run independently.
"""

import os
import json
import random
import traceback
from dotenv import load_dotenv
load_dotenv()

from openai import OpenAI
from llama_api_client import LlamaAPIClient
from anthropic import Anthropic
from google import genai

# API keys from .env
openai_client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
)

# Llama API died on July 6th, 2026... RIP.
# llama_client = LlamaAPIClient(
#     api_key=os.environ.get("LLAMA_API_KEY"),
# )

anthropic_client = Anthropic(
    api_key=os.environ.get("ANTHROPIC_API_KEY"),
)

gemini_client = genai.Client()

# prompt base that will be injected with the abstract (may need some tweaking)
prompt_base = (
    "Acting as an academic expert, generate one one-sentence scientific "
    "question that scholars might ask about a piece of scientific literature, "
    "based on a specific abstract from a scientific paper, which is provided after the keyword 'Abstract:'. The question should "
    "require the synthesis of multiple scientific papers to answer (a "
    "literature-review style question). Abstract:"
)

ALL_LLMS = ["openai", "anthropic", "gemini"]

# 1a. Load current JSON, if it exists. Build off of this.
# (Safeguard for if it crashes in the middle, can pick up where it left off)
def load_file(filename):
    if os.path.exists(filename):
        with open(filename, "r") as f:
            return json.load(f)
    return []


# 1b. Parse the abstracts JSON for an abstract; cross-check ids of abstract
# JSON and current JSON being build to ensure that an abstract
# has not been prompted with yet (checks using OpenAlex id, given in json formatting for abstracts)
def completed_abstract_ids(filename):
    content = load_file(filename)
    return [entry["id"] for entry in content]

# Inject the abstract into the prompt base.
def build_prompt(abstract):
    return f"{prompt_base} {abstract}"

# Calls a given LLM and returns the generated question. If llm is "testing", returns a placeholder question.
def prompt_llm(prompt, llm):
    if llm == "openai":
        response = openai_client.chat.completions.create(
            model="gpt-5.5",
            messages=[{"role": "user", "content": prompt}],
        )
        return response.choices[0].message.content

    # RIP LLama.
    # elif llm == "llama":
        # response = llama_client.chat.completions.create(
        #     messages=[{"content": prompt, "role": "user"}],
        #     model="model",  # TODO: set real model name
        # )
        # return response["completion_message"]["content"]["text"]

    elif llm == "anthropic":
        response = anthropic_client.messages.create(
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
            model="claude-opus-4-8",
        )
        if not response.content:
            raise RuntimeError(f"Anthropic returned no content (stop_reason={response.stop_reason})")
        return response.content[0].text

    elif llm == "gemini":
        response = gemini_client.interactions.create(
            model="gemini-3.5-flash",
            input=prompt
        )
        return response.output_text

    else:  # testing mode
        return "This is a test question and is not generated by an LLM. It is a placeholder for testing purposes."

# Append a new {id, model, question} entry to the output JSON file.
def build_json(filename, abstract_id, llm, question):
    output_file = load_file(filename)

    new_entry = {
        "id": abstract_id,
        "model": llm,
        "question": question.strip(),
    }

    output_file.append(new_entry)
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w") as f:
        json.dump(output_file, f, indent=2)


def generate_questions(abstracts_file, output_file):
    """
    Reads 100 abstracts from abstracts_file, prompts 3 LLMs to generate questions, and saves the questions to output_file.

    WHY? Each abstract list can have questions generated by multiple LLMs, so that LLMs are evenly divided across the abstracts. 
    This ensures that LLMs are not biased by the formatting of a specific question by balancing all LLMs.
    -> (i.e. Claude generates questions that Claude is especially good at answering).

    If the assigned LLM fails (e.g. refusal, quota, access issue), falls back to trying
    the other two LLMs in order before giving up on that abstract entirely.
    """
    abstracts = load_file(abstracts_file)
    completed_abstracts = completed_abstract_ids(output_file)

    llms = ["openai", "anthropic", "gemini"]

    # since there are 100 abstracts, select 33 abstracts for each LLM to generate questions for,
    # and the remaining 1 abstract is randomly assigned to one of the LLMs.
    llm_assignments = (
        [llms[0]] * 33 +
        [llms[1]] * 33 +
        [llms[2]] * 33 +
        [random.choice(llms)]
    )

    skipped = []
    fallbacks_used = []

    for abstract, assigned_llm in zip(abstracts, llm_assignments):
        abstract_id = abstract["id"]
        if abstract_id in completed_abstracts:
            continue

        prompt = build_prompt(abstract["abstract"])

        # try the assigned LLM first, then fall back to the others in order
        fallback_order = [assigned_llm] + [l for l in ALL_LLMS if l != assigned_llm]

        success = False
        for attempt_llm in fallback_order:
            try:
                question = prompt_llm(prompt, attempt_llm)
                build_json(output_file, abstract_id, attempt_llm, question)
                if attempt_llm != assigned_llm:
                    print(f"Fallback: {abstract_id} assigned to {assigned_llm}, "
                          f"succeeded with {attempt_llm} instead")
                    fallbacks_used.append({
                        "id": abstract_id,
                        "assigned": assigned_llm,
                        "used": attempt_llm,
                    })
                success = True
                break
            except Exception as e:
                print(f"{attempt_llm} failed for {abstract_id}: {type(e).__name__}: {e}")
                traceback.print_exc()
                continue

        if not success:
            print(f"--- All LLMs failed for {abstract_id}, skipping entirely ---")
            skipped.append({"id": abstract_id, "assigned_llm": assigned_llm})

    if fallbacks_used:
        print(f"\n{len(fallbacks_used)} abstract(s) used a fallback LLM:")
        for f in fallbacks_used:
            print(f"  - {f['id']}: assigned {f['assigned']} -> used {f['used']}")

    if skipped:
        print(f"\n{len(skipped)} abstract(s) skipped entirely in {output_file} (all LLMs failed):")
        for s in skipped:
            print(f"  - {s['id']} (assigned {s['assigned_llm']})")

    print(f"\nDone. Questions saved to {output_file}")



if __name__ == "__main__":

    generate_questions(abstracts_file="data/abstracts/abstracts_s86852077.json", output_file="data/questions/questions_s86852077.json")
    generate_questions(abstracts_file="data/abstracts/abstracts_S110447773.json", output_file="data/questions/questions_S110447773.json")
    generate_questions(abstracts_file="data/abstracts/abstracts_S145089992.json", output_file="data/questions/questions_S145089992.json")
    generate_questions(abstracts_file="data/abstracts/abstracts_S4210175523.json", output_file="data/questions/questions_S4210175523.json")