"""
Isolates the question-generating task (TASK1) from the rest of the code in prompt_llm.py, so that it can be run independently.
"""

import os
import json
import random
import time
from collections import deque
from dotenv import load_dotenv
load_dotenv()

from openai import OpenAI
from llama_api_client import LlamaAPIClient
from anthropic import Anthropic
from google import genai

# API keys from .env
openai_client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
)

# Llama API died on July 6th, 2026... RIP.
# llama_client = LlamaAPIClient(
#     api_key=os.environ.get("LLAMA_API_KEY"),
# )

anthropic_client = Anthropic(
    api_key=os.environ.get("ANTHROPIC_API_KEY"),
)

gemini_client = genai.Client()

# prompt base that will be injected with the abstract (may need some tweaking)
prompt_base = (
    "Acting as an academic expert, generate one one-sentence scientific "
    "question that scholars might ask about a piece of scientific literature, "
    "based on a specific abstract from a scientific paper, which is provided after the keyword 'Abstract:'. The question should "
    "require the synthesis of multiple scientific papers to answer (a "
    "literature-review style question). Abstract:"
)

# Gemini free tier: 5 requests per 60s window. Track call timestamps and
# sleep just long enough to stay under the limit.
_gemini_call_times = deque()
GEMINI_MAX_CALLS = 5
GEMINI_WINDOW_SECONDS = 60

def _gemini_rate_limit():
    now = time.time()
    # drop timestamps older than the window
    while _gemini_call_times and now - _gemini_call_times[0] > GEMINI_WINDOW_SECONDS:
        _gemini_call_times.popleft()

    if len(_gemini_call_times) >= GEMINI_MAX_CALLS:
        sleep_time = GEMINI_WINDOW_SECONDS - (now - _gemini_call_times[0]) + 1  # +1s buffer
        print(f"Gemini rate limit reached, sleeping {sleep_time:.1f}s...")
        time.sleep(sleep_time)

    _gemini_call_times.append(time.time())


# 1a. Load current JSON, if it exists. Build off of this.
# (Safeguard for if it crashes in the middle, can pick up where it left off)
def load_file(filename):
    if os.path.exists(filename):
        with open(filename, "r") as f:
            return json.load(f)
    return []


# 1b. Parse the abstracts JSON for an abstract; cross-check ids of abstract
# JSON and current JSON being build to ensure that an abstract
# has not been prompted with yet (checks using OpenAlex id, given in json formatting for abstracts)
def completed_abstract_ids(filename):
    content = load_file(filename)
    return [entry["id"] for entry in content]

# Inject the abstract into the prompt base.
def build_prompt(abstract):
    return f"{prompt_base} {abstract}"

# Calls a given LLM and returns the generated question. If llm is "testing", returns a placeholder question.
def prompt_llm(prompt, llm):
    if llm == "openai":
        response = openai_client.chat.completions.create(
            model="gpt-5.5",
            messages=[{"role": "user", "content": prompt}],
        )
        return response.choices[0].message.content

    # RIP LLama.
    # elif llm == "llama":
        # response = llama_client.chat.completions.create(
        #     messages=[{"content": prompt, "role": "user"}],
        #     model="model",  # TODO: set real model name
        # )
        # return response["completion_message"]["content"]["text"]

    elif llm == "anthropic":
        response = anthropic_client.messages.create(
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
            model="claude-opus-4-8",
        )
        return response.content[0].text

    elif llm == "gemini":
        _gemini_rate_limit()
        response = gemini_client.interactions.create(
            model="gemini-3.5-flash",
            input=prompt
        )
        return response.output_text

    else:  # testing mode
        return "This is a test question and is not generated by an LLM. It is a placeholder for testing purposes."

# Append a new {id, model, question} entry to the output JSON file.
def build_json(filename, abstract_id, llm, question):
    output_file = load_file(filename)

    new_entry = {
        "id": abstract_id,
        "model": llm,
        "question": question.strip(),
    }

    output_file.append(new_entry)
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w") as f:
        json.dump(output_file, f, indent=2)


def generate_questions(abstracts_file, output_file):
    """
    Reads 100 abstracts from abstracts_file, prompts 3 LLMs to generate questions, and saves the questions to output_file.
    
    WHY? Each abstract list can have questions generated by multiple LLMs, so that LLMs are evenly divided across the abstracts. 
    This ensures that LLMs are not biased by the formatting of a specific question by balancing all LLMs.
    -> (i.e. Claude generates questions that Claude is especially good at answering).
    """
    abstracts = load_file(abstracts_file)
    completed_abstracts = completed_abstract_ids(output_file)

    llms = ["openai", "anthropic", "gemini"]

    # since there are 100 abstracts, select 33 abstracts for each LLM to generate questions for,
    # and the remaining 1 abstract is randomly assigned to one of the LLMs.
    llm_assignments = (
        [llms[0]] * 33 +
        [llms[1]] * 33 +
        [llms[2]] * 33 +
        [random.choice(llms)]
    )

    skipped = []

    for abstract, llm in zip(abstracts, llm_assignments):
        abstract_id = abstract["id"]
        if abstract_id in completed_abstracts:
            continue

        prompt = build_prompt(abstract["abstract"])
        try:
            question = prompt_llm(prompt, llm)
            build_json(output_file, abstract_id, llm, question)
        except Exception as e:
            print(f"Skipping {abstract_id} ({llm}) due to error: {e}")
            skipped.append({"id": abstract_id, "llm": llm})
            continue

    if skipped:
        print(f"\n{len(skipped)} abstract(s) skipped due to errors:")
        for s in skipped:
            print(f"  - {s['id']} ({s['llm']})")
        print("Fix access/quota issues and rerun to fill these in.")

    print(f"\nDone. Questions saved to {output_file}")


if __name__ == "__main__":
    generate_questions(abstracts_file="data/abstracts/abstracts_S9692511.json", output_file="data/questions/questions_S9692511.json")
    generate_questions(abstracts_file="data/abstracts/abstracts_S1980519.json", output_file="data/questions/questions_S1980519.json") # didnt finish gemini yet